### ISSUE TITLE
Write Photo Filters Testing - Unit Testing

### ISSUE THREAD

**Issue by n2chao** [Earthii/Simple-Camera-SOEN-390#10]
Create tests for the new feature

[SP- 8]
[Risk - high]
[Priority - high]

## Tasks
Everyone is responsible to write the tests for the code they write.

User story: #9 

## Point division
3 - @n2chao 
3 - @Earthii 
2 - @StevenHaa

**Comment by Earthii** [comment]
This issue has a lot of hidden effort. Team has been trying to integrate Mocks and Robolectric for a while
