### ISSUE TITLE
Emulator grid scaling bug

### ISSUE THREAD

**Issue by Ea10** [Earthii/Simple-Camera-SOEN-390#100]
[SP - 1]
[Risk - Low]
[Priority - Low]

There is an edge case with grids currently when running the app on a Nexus 5 in emulator, the target phone for the application. A different aspect ratio appears when running on emulator that doesn't appear on a real life nexus 5. This different aspect ratio does not change regardless of resolution selection.

**Comment by StevenHaa** [comment]
weird bug, hopefully we don't have many edge cases like this ( where the bug appears in the emulator but not on a real life phone)

**Comment by Earthii** [comment]
Implemented in #101
