### ISSUE TITLE
As a user I should be able to have image recognition

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#105]
[SP - 20]
[Risk - Medium]
[Priority - High]

## Task

- [ ] Mockup, 1sp
- [ ] Acceptance test, 1sp

**Comment by StevenHaa** [comment]
lets use clarafai api for image recognition?

**Comment by jinfuchen** [comment]
Make this feature lower priority. If you want to implement this feature, choose one simple object.

**Comment by Earthii** [comment]
Here is the asset for the mockup 
![imageedit_6_6633903786](https://user-images.githubusercontent.com/16367621/38761253-1abeca20-3f4f-11e8-82c2-e979410dc374.png)

**Comment by Earthii** [comment]
we have the connection to clarifai open, but i dont think we'll be able to finish the entire feature
