### ISSUE TITLE
UI tests for features of sprint 5

### ISSUE THREAD

**Issue by Ea10** [Earthii/Simple-Camera-SOEN-390#124]
[SP - 3]
[Risk - Medium]
[Priority - High]

- [x] Scanning phone numbers UI 2sp - @Ea10
- [x] Geolocation UI 1sp - @Earthii

**Comment by n2chao** [comment]
UI tests for geolocation are in PR #121

**Comment by Ea10** [comment]
UI tests for number scan are in PR #130
