### ISSUE TITLE
Add Icons to the filter buttons

### ISSUE THREAD

**Issue by Earthii** [Earthii/Simple-Camera-SOEN-390#16]
Extra for #8 

[SP - 2]
[Risk - Medium]
[Priority - Medium]

## Task

- [x] add correct icons to filter toggle @Ea10

**Comment by Ea10** [comment]
![image](https://user-images.githubusercontent.com/25261046/36038754-8c73de0a-0d8e-11e8-9539-db56f9212d51.png)

**Comment by Earthii** [comment]
PR #23
