### ISSUE TITLE
Mockup showing the filter feature

### ISSUE THREAD

**Issue by Earthii** [Earthii/Simple-Camera-SOEN-390#17]
Create a mock up showing how to use the filtering

[SP - 2]
[Risk - low]
[Priority - High]

## Task
- [x] create mockup for remember filter
- [x] create mockup for apply filter

**Comment by nemotime** [comment]
![filtermockup](https://user-images.githubusercontent.com/14989693/36088538-a935cad0-0fa5-11e8-9646-110d162e1e44.jpg)
