### ISSUE TITLE
Installing CI Infrastructure - Travis

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#2]
The application should be in continuous integration. Connect the application to travis CI to test builds.

[SP - 3]
[Risk - Medium]
[Priority - High]

## Task

- [x] Connect Repo to Travis CI
- [x] Make the CI pass

**Comment by Earthii** [comment]
Done 
[Travis CI for Simple-Camera-SOEN-390](https://travis-ci.org/Earthii/Simple-Camera-SOEN-390)

**Comment by jinfuchen** [comment]
Done
