### ISSUE TITLE
Write Remember Filters Testing - Unit Testing

### ISSUE THREAD

**Issue by Earthii** [Earthii/Simple-Camera-SOEN-390#29]
#14 

[SP- 3]
[Risk - Medium]
[Priority - High]

## Task
- [x] Test that the last filter variable is set
- [x] Test that the Keep last filter switch is present

**Comment by Earthii** [comment]
missing the check on the existance of buttons i n the settings

**Comment by nemotime** [comment]
Finished adding check of existence of button in settings
