### ISSUE TITLE
Recovery of the architecture 

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#4]
Produce the component diagram of Simple-Camera 

[SP - 5]
[Risk - High]
[Priority - Medium]

## Task
- [x] Inspect Code
- [ ] Produce Diagram

**Comment by Earthii** [comment]
Discussed with TA, Simple Camera is a application that is very small

A class diagram is sufficient

**Comment by jinfuchen** [comment]
Extract class diagram.
