### ISSUE TITLE
Mockup for countdown feature

### ISSUE THREAD

**Issue by Earthii** [Earthii/Simple-Camera-SOEN-390#52]
[SP -2]
[Risk - low]
[Priority - High]

**Comment by nemotime** [comment]
![countdownfeature](https://user-images.githubusercontent.com/14989693/36655570-778d8242-1a91-11e8-8e8e-10a7a97624a7.jpg)

**Comment by Ea10** [comment]
Story points for this issue are now included in the respective user story.
