### ISSUE TITLE
Mockup for taking photo while recording videos

### ISSUE THREAD

**Issue by Earthii** [Earthii/Simple-Camera-SOEN-390#53]
[SP - 2]
[Risk - low]
[Priority -High]

**Comment by nemotime** [comment]
![imgwhilerecording](https://user-images.githubusercontent.com/14989693/36657539-07c596f2-1a9b-11e8-8dd4-edb967052249.jpg)

<div>Check icon made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

<div>Shutter icon made by <a href="https://www.flaticon.com/authors/bogdan-rosu" title="Bogdan Rosu">Bogdan Rosu</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

**Comment by Ea10** [comment]
Story points for this issue are now included in the respective user story.
