### ISSUE TITLE
Create Mockups 

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#6]
Produce a mock-up for a basic feature for simple camera.

[SP - 2]
[Risk - Low]
[Priority - Medium]

**Comment by nemotime** [comment]
![Mockup](https://user-images.githubusercontent.com/14989693/35607555-bc5012e2-0622-11e8-92dc-64c28098d4e2.png)

**Comment by nemotime** [comment]
![Mockup](https://user-images.githubusercontent.com/14989693/35608376-df2ab14c-0626-11e8-81ca-eed9992df6b3.png)
<div>Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

**Comment by StevenHaa** [comment]
maybe you couldve used different colors for the lines to make it easier to see instead of just all red, but none the less, goodjob

**Comment by jinfuchen** [comment]
This is the whole project's mockups. 
I have a little confuse that why the "View camera Roll" is empty.

**Comment by n2chao** [comment]
@jinfuchen The "view camera roll" is not part of the application. There is no camera roll included in the app as it uses the default of your phone.
