### ISSUE TITLE
BUG - If the camera does not support taking a picture while recording, the toggle camera icon/shutter icon should not be visible

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#77]
[SP - 1]
[Risk - low]
[Priority - HIGH]

No icons should appear while recording if the phone does not support capturing photo while recording

**Comment by nemotime** [comment]
Do we know what API level this starts at? Or is it a feature only some phones have?

**Comment by StevenHaa** [comment]
As far as I know, it works on Nathans old phone which is a Nexus 5, and when we ran an emulator with Nexus 5 with api 27, it failed.. so it might be api? I am not certain though

**Comment by younesstawil** [comment]
I ran it on 2.7 QVGA api 22(emulator) and it works fine. it does not show the icon as expected. As Steven said the API we are using is deprecated so we can not be sure what is the problem.
