### ISSUE TITLE
As A user, I should be able to swipe to trigger video mode

### ISSUE THREAD

**Issue by Earthii** [Earthii/Simple-Camera-SOEN-390#84]
As a user if i swipe left/right, i should be able to go from picture mode to video mode etc.

[SP - 8]
[Priority - High]
[Risk - Medium]

## Task

- [x] Create the On swipe listener class, listener to the preview, Acceptance Test, Mockup [Eric 5 SP]
- [x] Add the Features to the appropriate swipes [Steven 3 SP]

**Comment by Earthii** [comment]
User Story ID: #84 | Test Designed by: Eric Xiao
-- | --
Test Priority (Low/Medium/High): High | Test Designed date: March 18, 2018
Module Name: | Test Executed by: Eric Xiao
Test Title: A user may swipe Left or Right to toggle between video/picture mode | Test Execution date: March 18, 2018
Description: If a user decides to swipe the screen to the right, it will switch the camera into video mode. There should be an indicator to show which mode the camera is in currently. Swapping left will put back the camera into photo mode.

**Comment by Earthii** [comment]
<img width="783" alt="screen shot 2018-03-16 at 3 53 36 pm" src="https://user-images.githubusercontent.com/16367621/37542179-b3676e3a-2933-11e8-8a3d-13c822b67c06.png">

**Comment by jinfuchen** [comment]
please add your mockups in the story.

**Comment by Earthii** [comment]
I created a class in the helper package that will handle all kinds of swipe action. It is a listener object.

When you want to use the listener, do it like this in kotlin:

object: OnSwipeTouchListener(activity){
...
}
and override the swipe methods

**Comment by StevenHaa** [comment]
Which direction do you think is best to swipe to video mode? And should we also make it swipe to camera mode?

**Comment by Earthii** [comment]
I think swipe left is the best to swap to video mode

**Comment by Earthii** [comment]
<img width="590" alt="screen shot 2018-03-16 at 6 15 50 pm" src="https://user-images.githubusercontent.com/16367621/37547217-a38f5d3e-2946-11e8-9d50-8d485cb76d19.png">

**Comment by Earthii** [comment]
<img width="792" alt="screen shot 2018-03-16 at 6 18 47 pm" src="https://user-images.githubusercontent.com/16367621/37547223-ab10365a-2946-11e8-91c4-3ea89f964570.png">

**Comment by Earthii** [comment]
<img width="796" alt="screen shot 2018-03-16 at 6 21 32 pm" src="https://user-images.githubusercontent.com/16367621/37547252-e13e176a-2946-11e8-9bec-acde55994474.png">

**Comment by Earthii** [comment]
<img width="802" alt="screen shot 2018-03-16 at 6 23 03 pm" src="https://user-images.githubusercontent.com/16367621/37547284-18905052-2947-11e8-8c42-2e843a637b76.png">

**Comment by Earthii** [comment]
![Uploading Screen Shot 2018-03-16 at 6.24.46 PM.png…]()

**Comment by Earthii** [comment]
<img width="801" alt="screen shot 2018-03-16 at 6 24 46 pm" src="https://user-images.githubusercontent.com/16367621/37547351-88484710-2947-11e8-83dd-1d6d46e1185c.png">

**Comment by Earthii** [comment]
<img width="586" alt="screen shot 2018-03-16 at 6 24 06 pm" src="https://user-images.githubusercontent.com/16367621/37547356-906fbdba-2947-11e8-900a-800dbe12b6fd.png">

**Comment by Earthii** [comment]
<img width="797" alt="screen shot 2018-03-16 at 6 26 52 pm" src="https://user-images.githubusercontent.com/16367621/37547364-a06f7dcc-2947-11e8-996b-3abcccaf4fca.png">

**Comment by StevenHaa** [comment]
I dont think the acceptance test is correct, the final step changes it back to "photo" mode but you wrote that the post condition is in video mode

**Comment by Earthii** [comment]
<img width="801" alt="screen shot 2018-03-16 at 6 31 16 pm" src="https://user-images.githubusercontent.com/16367621/37547471-43982cf6-2948-11e8-9680-87dc598e3417.png">

**Comment by Earthii** [comment]
You are right, I updated it

**Comment by Earthii** [comment]
<img width="793" alt="screen shot 2018-03-16 at 6 32 27 pm" src="https://user-images.githubusercontent.com/16367621/37547496-69e95c72-2948-11e8-983e-c7a6b635adbe.png">

**Comment by Earthii** [comment]
#85
