### ISSUE TITLE
BUG - switching between photo and video mode from the  setting menu does not change the focus on the words

### ISSUE THREAD

**Issue by younesstawil** [Earthii/Simple-Camera-SOEN-390#86]
Not only swiping should change the focus on "PHOTO" and "VIDEO" it should change every time the mode changes. #84 #85

**Comment by younesstawil** [comment]
triggered fadePhotoVideo() method when appropriate to fix

**Comment by StevenHaa** [comment]
considering we now have this swipe feature, we might just remove the functionality from the setting menu- need to discuss with the team, but good fix for now.
