### ISSUE TITLE
As a User, I should be able to apply Photo Filters on the live preview

### ISSUE THREAD

**Issue by n2chao** [Earthii/Simple-Camera-SOEN-390#9]
As a user, I want to take pictures with color filters to enhance my pictures.

[SP - 20]
[Risk - Medium]
[Priority - High]

## Related Tasks
#8 Create a button which toggles filters(8 SP)
#10 Write photo filters testing (5 SP)
#11 Apply filter (5 SP)
#16 Add icons to the filter buttons (2 SP)

**Comment by Earthii** [comment]
PR #20

**Comment by jinfuchen** [comment]
Demo applying Photo Filters on the live preview. 
#8 Create a button which toggles filters(done)
#11 Apply filter (done)
#16 Add icons to the filter buttons (done)
Implement three unit tests and run successfully.
List 5 acceptance tests for the feature of applying photo filter on the live preview.
