### ISSUE TITLE
Unit tests for grid overlay feature

### ISSUE THREAD

**Issue by Ea10** [Earthii/Simple-Camera-SOEN-390#91]
[SP - 2]
[Risk - Medium]
[Priority - Medium]

**Comment by Earthii** [comment]
You can do something similar to Keep Last filter for this unit test

**Comment by nemotime** [comment]
I agree with @Earthii, it is a very straight forward feature.

**Comment by StevenHaa** [comment]
lets do that next sprint @Earthii  and @nemotime
