### ISSUE TITLE
UI tests for features of Sprint 4

### ISSUE THREAD

**Issue by Ea10** [Earthii/Simple-Camera-SOEN-390#98]
[SP - 5]
[Risk - Medium]
[Priority - High]

- [x] Grid overlay UI (Ethan -2 SP)
- [x] Swipe to trigger video UI (Steven -  1SP)
- [x] Smile detection UI (Nathan - 2 SP)

**Comment by StevenHaa** [comment]
i worked on the Swiping between photo and video so i finished that UI test. @Ea10  can do the grid Ui test and @n2chao  can work on the smile detection ui test

**Comment by n2chao** [comment]
The UI test for the smile detection is done. The test verifies that the smile button is there and that it switches to the new activity when pressed.
